### ISSUE TITLE
HomePageFragment

### ISSUE THREAD

**Issue by dignacio0815** [fbu-aad/FBU-AAD-team-project#15]

**Comment by dignacio0815** [comment]
- [ ] Nested Recycler View holding different charities based on featured, recommended, and friends charities

**Comment by chiped** [comment]
Since we don't have the API setup yet, you can have the items in recycler view have just one text view with a number


| Featured |
| 1 | 2 | 3 | 4 | 5 | 6 | 7 |

| Recommended |
| 11 | 12 | 13 | 14 | 15 | 16 | 17 |

| Friends |
| 21 | 22 | 23 | 24 | 25 | 26 | 27 |

**Comment by chiped** [comment]
addressed by #27
